language: node_js

node_js:
  - "v12.6.0"

cache:
  directories:
    - "node_modules"

env:
  global:
    - SHOCKPKG_VERIFY_RETRY_DELAY=10000

script:
  - npm run clean
  - npm run lint
  - npm run test
  - npm run verify
  # - npm run newest
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: dist
  target-branch: gh-pages
  committer-from-gh: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
    condition: $TRAVIS_EVENT_TYPE != cron
