language: node_js

node_js:
  - "v10.6.0"

cache:
  yarn: true
  directories:
    - "node_modules"

script:
  - yarn run lint
  - yarn run test

after_success:
  - test $TRAVIS_BRANCH = "master" && echo ./updateapi.sh
